const { DishReviews } = require("../models");

const dishReviewsData = [
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 1,
    user_id: null,
  },
  {
    rating: 4,
    review: "Pretty good!",
    dish_id: 2,
    user_id: null,
  },
  {
    rating: 4,
    review: "Not bad, not great",
    dish_id: 3,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 4,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 5,
    user_id: null,
  },
  {
    rating: 2,
    review: "So so...",
    dish_id: 6,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 7,
    user_id: null,
  },
  {
    rating: 5,
    review: "Such a good salad!",
    dish_id: 8,
    user_id: null,
  },
  {
    rating: 2,
    review: "Amazing!",
    dish_id: 9,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best kung pao in town!",
    dish_id: 1,
    user_id: null,
  },
  {
    rating: 4,
    review: "So tasty!",
    dish_id: 2,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 3,
    user_id: null,
  },
  {
    rating: 5,
    review: "So fresh!",
    dish_id: 4,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 5,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 6,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 7,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 8,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 9,
    user_id: null,
  },
  {
    rating: 5,
    review: "I could eat this every day!",
    dish_id: 1,
    user_id: null,
  },
  {
    rating: 5,
    review: "Delicious!",
    dish_id: 2,
    user_id: null,
  },
  {
    rating: 5,
    review: "Amazing!",
    dish_id: 3,
    user_id: null,
  },
  {
    rating: 5,
    review: "Delicious! Filling but not super heavy!",
    dish_id: 4,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 5,
    user_id: null,
  },
  {
    rating: 5,
    review:
      "Saw some other reviews rating it poorly and I cannot imagine why! So good!",
    dish_id: 6,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 7,
    user_id: null,
  },
  {
    rating: 3,
    review: "Was hoping it would be better...",
    dish_id: 8,
    user_id: null,
  },
  {
    rating: 2,
    review: "Amazing!",
    dish_id: 9,
    user_id: null,
  },
  {
    rating: 3,
    review: "Had higher hopes...",
    dish_id: 1,
    user_id: null,
  },
  {
    rating: 1,
    review: "So good!",
    dish_id: 2,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 3,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 4,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 5,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 6,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 7,
    user_id: null,
  },
  {
    rating: 5,
    review: "o good!",
    dish_id: 8,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 9,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 1,
    user_id: null,
  },
  {
    rating: 4,
    review: "Pretty good!",
    dish_id: 2,
    user_id: null,
  },
  {
    rating: 4,
    review: "Not bad, not great",
    dish_id: 3,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 4,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 5,
    user_id: null,
  },
  {
    rating: 2,
    review: "So so...",
    dish_id: 6,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 7,
    user_id: null,
  },
  {
    rating: 5,
    review: "Such a good salad!",
    dish_id: 8,
    user_id: null,
  },
  {
    rating: 2,
    review: "Amazing!",
    dish_id: 9,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in town!",
    dish_id: 1,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 2,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 3,
    user_id: null,
  },
  {
    rating: 5,
    review: "Was so fresh!",
    dish_id: 4,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 5,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 6,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 7,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 8,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 9,
    user_id: null,
  },
  {
    rating: 5,
    review: "I could eat this every day!",
    dish_id: 1,
    user_id: null,
  },
  {
    rating: 5,
    review: "That's some tasty stuff!",
    dish_id: 2,
    user_id: null,
  },
  {
    rating: 5,
    review: "Amazing!",
    dish_id: 3,
    user_id: null,
  },
  {
    rating: 5,
    review: "Delicious! Filling but not super heavy!",
    dish_id: 4,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 5,
    user_id: null,
  },
  {
    rating: 5,
    review:
      "Saw some other reviews rating it poorly and I cannot imagine why! So good!",
    dish_id: 6,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 7,
    user_id: null,
  },
  {
    rating: 3,
    review: "Was hoping for more..",
    dish_id: 8,
    user_id: null,
  },
  {
    rating: 2,
    review: "Eh.",
    dish_id: 9,
    user_id: null,
  },
  {
    rating: 3,
    review: "Had higher hopes...",
    dish_id: 10,
    user_id: null,
  },
  {
    rating: 1,
    review: "Best meatball sandwich in the world!!!",
    dish_id: 10,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 10,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 11,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 11,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 11,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 12,
    user_id: null,
  },
  {
    rating: 5,
    review: "Get it with the mustard vinaigrette! So good!",
    dish_id: 12,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 12,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 13,
    user_id: null,
  },
  {
    rating: 4,
    review: "Pretty good!",
    dish_id: 13,
    user_id: null,
  },
  {
    rating: 4,
    review: "Not bad, not great",
    dish_id: 13,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 14,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 14,
    user_id: null,
  },
  {
    rating: 2,
    review: "So so...",
    dish_id: 14,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 15,
    user_id: null,
  },
  {
    rating: 5,
    review: "Such a good salad!",
    dish_id: 15,
    user_id: null,
  },
  {
    rating: 2,
    review: "Amazing!",
    dish_id: 15,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best breakfast sando in town!",
    dish_id: 16,
    user_id: null,
  },
  {
    rating: 1,
    review: "Best meatball sandwich in the world!!!",
    dish_id: 16,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 16,
    user_id: null,
  },
  {
    rating: 5,
    review: "The pesto was so fresh!",
    dish_id: 17,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 17,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 17,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 18,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 18,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 18,
    user_id: null,
  },
  {
    rating: 5,
    review: "I could eat this every day!",
    dish_id: 19,
    user_id: null,
  },
  {
    rating: 5,
    review: "That's a spicy meatball!",
    dish_id: 19,
    user_id: null,
  },
  {
    rating: 5,
    review: "Amazing!",
    dish_id: 19,
    user_id: null,
  },
  {
    rating: 5,
    review: "Delicious! Filling but not super heavy!",
    dish_id: 20,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 20,
    user_id: null,
  },
  {
    rating: 5,
    review:
      "Saw some other reviews rating it poorly and I cannot imagine why! So good!",
    dish_id: 20,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 21,
    user_id: null,
  },
  {
    rating: 3,
    review: "Was hoping the chicken would be crispier",
    dish_id: 21,
    user_id: null,
  },
  {
    rating: 2,
    review: "Amazing!",
    dish_id: 21,
    user_id: null,
  },
  {
    rating: 3,
    review: "Had higher hopes...",
    dish_id: 22,
    user_id: null,
  },
  {
    rating: 1,
    review: "Best meatball sandwich in the world!!!",
    dish_id: 22,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 22,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 23,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 23,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 23,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 24,
    user_id: null,
  },
  {
    rating: 5,
    review: "Get it with the mustard vinaigrette! So good!",
    dish_id: 24,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 24,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 25,
    user_id: null,
  },
  {
    rating: 4,
    review: "Pretty good!",
    dish_id: 25,
    user_id: null,
  },
  {
    rating: 4,
    review: "Not bad, not great",
    dish_id: 25,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 26,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 26,
    user_id: null,
  },
  {
    rating: 2,
    review: "So so...",
    dish_id: 26,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 27,
    user_id: null,
  },
  {
    rating: 5,
    review: "Such a good salad!",
    dish_id: 27,
    user_id: null,
  },
  {
    rating: 2,
    review: "Amazing!",
    dish_id: 27,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best breakfast sando in town!",
    dish_id: 28,
    user_id: null,
  },
  {
    rating: 1,
    review: "Best meatball sandwich in the world!!!",
    dish_id: 28,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 28,
    user_id: null,
  },
  {
    rating: 5,
    review: "The pesto was so fresh!",
    dish_id: 29,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 29,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 29,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 30,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 30,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 30,
    user_id: null,
  },
  {
    rating: 5,
    review: "I could eat this every day!",
    dish_id: 31,
    user_id: null,
  },
  {
    rating: 5,
    review: "That's a spicy meatball!",
    dish_id: 31,
    user_id: null,
  },
  {
    rating: 5,
    review: "Amazing!",
    dish_id: 31,
    user_id: null,
  },
  {
    rating: 5,
    review: "Delicious! Filling but not super heavy!",
    dish_id: 32,
    user_id: null,
  },
  {
    rating: 5,
    review: "Best in the world!!!",
    dish_id: 32,
    user_id: null,
  },
  {
    rating: 5,
    review:
      "Saw some other reviews rating it poorly and I cannot imagine why! So good!",
    dish_id: 32,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 33,
    user_id: null,
  },
  {
    rating: 3,
    review: "Was hoping the chicken would be crispier",
    dish_id: 33,
    user_id: null,
  },
  {
    rating: 2,
    review: "Amazing!",
    dish_id: 33,
    user_id: null,
  },
  {
    rating: 3,
    review: "Had higher hopes...",
    dish_id: 34,
    user_id: null,
  },
  {
    rating: 1,
    review: "Best meatball sandwich in the world!!!",
    dish_id: 34,
    user_id: null,
  },
  {
    rating: 2,
    review: "Average",
    dish_id: 34,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 35,
    user_id: null,
  },
  {
    rating: 4,
    review: "Awesome!!!",
    dish_id: 35,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 35,
    user_id: null,
  },
  {
    rating: 5,
    review: "This is the bomb!",
    dish_id: 36,
    user_id: null,
  },
  {
    rating: 5,
    review: "Get it with the mustard vinaigrette! So good!",
    dish_id: 36,
    user_id: null,
  },
  {
    rating: 4,
    review: "Amazing!",
    dish_id: 36,
    user_id: null,
  },
];

const seedDishReviews = () => DishReviews.bulkCreate(dishReviewsData);

module.exports = seedDishReviews;
